export enum BlockType {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  COBBLESTONE = 4,
  WOOD_LOG = 5,
  WOOD_PLANKS = 6,
  LEAVES = 7,
  GLASS = 8,
  BRICKS = 9,
  SAND = 10,
  WATER = 11,
  COAL_ORE = 12,
  IRON_ORE = 13,
  GOLD_ORE = 14,
  DIAMOND_ORE = 15,
  SNOW = 16,
  CACTUS = 17,
  FLOWER_RED = 18,
  FLOWER_YELLOW = 19,
  TORCH = 20,
  TNT = 21,
  BEDROCK = 22,
  OBSIDIAN = 23,
  BOOKSHELF = 24,
  CRAFTING_TABLE = 25,
  STICK = 26,
  WOODEN_PICKAXE = 27,
  STONE_PICKAXE = 28,
  IRON_PICKAXE = 29,
  DIAMOND_PICKAXE = 30,
  WOODEN_AXE = 31,
  STONE_AXE = 32,
  WOODEN_SHOVEL = 33,
  STONE_SHOVEL = 34,
  WOODEN_SWORD = 35,
  STONE_SWORD = 36,
  FURNACE = 37,
  ROTTEN_FLESH = 38,
  BONE = 39,
  ARROW = 40,
  BOW = 41,
}

export type SoundCategory = 'grass' | 'wood' | 'stone' | 'glass' | 'sand' | 'wool';

export interface BlockMeta {
  id: BlockType;
  name: string;
  nameEn: string;
  isTransparent: boolean;
  isSolid: boolean;
  isLiquid?: boolean;
  emitsLight?: number; // 0 to 15
  hardness: number; // breaking time in seconds (0 = instant, e.g. flowers)
  sound: SoundCategory;
  dropBlock: BlockType;
  dropCount: number;
  isTool?: boolean;
  toolType?: 'pickaxe' | 'axe' | 'shovel' | 'sword';
  speedMultiplier?: number;
}

export const BLOCK_METAS: Record<BlockType, BlockMeta> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: 'Ar',
    nameEn: 'Air',
    isTransparent: true,
    isSolid: false,
    hardness: 0,
    sound: 'grass',
    dropBlock: BlockType.AIR,
    dropCount: 0,
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Bloco de Grama',
    nameEn: 'Grass Block',
    isTransparent: false,
    isSolid: true,
    hardness: 0.6,
    sound: 'grass',
    dropBlock: BlockType.DIRT,
    dropCount: 1,
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Terra',
    nameEn: 'Dirt',
    isTransparent: false,
    isSolid: true,
    hardness: 0.5,
    sound: 'grass',
    dropBlock: BlockType.DIRT,
    dropCount: 1,
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Pedra',
    nameEn: 'Stone',
    isTransparent: false,
    isSolid: true,
    hardness: 1.5,
    sound: 'stone',
    dropBlock: BlockType.COBBLESTONE,
    dropCount: 1,
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Pedregulho',
    nameEn: 'Cobblestone',
    isTransparent: false,
    isSolid: true,
    hardness: 1.8,
    sound: 'stone',
    dropBlock: BlockType.COBBLESTONE,
    dropCount: 1,
  },
  [BlockType.WOOD_LOG]: {
    id: BlockType.WOOD_LOG,
    name: 'Tronco de Carvalho',
    nameEn: 'Oak Log',
    isTransparent: false,
    isSolid: true,
    hardness: 1.2,
    sound: 'wood',
    dropBlock: BlockType.WOOD_LOG,
    dropCount: 1,
  },
  [BlockType.WOOD_PLANKS]: {
    id: BlockType.WOOD_PLANKS,
    name: 'Tábua de Madeira',
    nameEn: 'Oak Planks',
    isTransparent: false,
    isSolid: true,
    hardness: 1.0,
    sound: 'wood',
    dropBlock: BlockType.WOOD_PLANKS,
    dropCount: 1,
  },
  [BlockType.LEAVES]: {
    id: BlockType.LEAVES,
    name: 'Folhas',
    nameEn: 'Leaves',
    isTransparent: true,
    isSolid: true,
    hardness: 0.2,
    sound: 'grass',
    dropBlock: BlockType.AIR,
    dropCount: 0,
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: 'Vidro',
    nameEn: 'Glass',
    isTransparent: true,
    isSolid: true,
    hardness: 0.3,
    sound: 'glass',
    dropBlock: BlockType.AIR,
    dropCount: 0,
  },
  [BlockType.BRICKS]: {
    id: BlockType.BRICKS,
    name: 'Tijolos',
    nameEn: 'Bricks',
    isTransparent: false,
    isSolid: true,
    hardness: 2.0,
    sound: 'stone',
    dropBlock: BlockType.BRICKS,
    dropCount: 1,
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Areia',
    nameEn: 'Sand',
    isTransparent: false,
    isSolid: true,
    hardness: 0.5,
    sound: 'sand',
    dropBlock: BlockType.SAND,
    dropCount: 1,
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: 'Água',
    nameEn: 'Water',
    isTransparent: true,
    isSolid: false,
    isLiquid: true,
    hardness: 100,
    sound: 'grass',
    dropBlock: BlockType.AIR,
    dropCount: 0,
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    name: 'Minério de Carvão',
    nameEn: 'Coal Ore',
    isTransparent: false,
    isSolid: true,
    hardness: 2.2,
    sound: 'stone',
    dropBlock: BlockType.TORCH,
    dropCount: 2,
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    name: 'Minério de Ferro',
    nameEn: 'Iron Ore',
    isTransparent: false,
    isSolid: true,
    hardness: 2.8,
    sound: 'stone',
    dropBlock: BlockType.IRON_ORE,
    dropCount: 1,
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    name: 'Minério de Ouro',
    nameEn: 'Gold Ore',
    isTransparent: false,
    isSolid: true,
    hardness: 3.0,
    sound: 'stone',
    dropBlock: BlockType.GOLD_ORE,
    dropCount: 1,
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    name: 'Minério de Diamante',
    nameEn: 'Diamond Ore',
    isTransparent: false,
    isSolid: true,
    hardness: 4.0,
    sound: 'stone',
    dropBlock: BlockType.DIAMOND_ORE,
    dropCount: 1,
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Neve',
    nameEn: 'Snow',
    isTransparent: false,
    isSolid: true,
    hardness: 0.4,
    sound: 'sand',
    dropBlock: BlockType.SNOW,
    dropCount: 1,
  },
  [BlockType.CACTUS]: {
    id: BlockType.CACTUS,
    name: 'Cacto',
    nameEn: 'Cactus',
    isTransparent: false,
    isSolid: true,
    hardness: 0.4,
    sound: 'grass',
    dropBlock: BlockType.CACTUS,
    dropCount: 1,
  },
  [BlockType.FLOWER_RED]: {
    id: BlockType.FLOWER_RED,
    name: 'Papoula Vermelha',
    nameEn: 'Red Poppy',
    isTransparent: true,
    isSolid: false,
    hardness: 0.05,
    sound: 'grass',
    dropBlock: BlockType.FLOWER_RED,
    dropCount: 1,
  },
  [BlockType.FLOWER_YELLOW]: {
    id: BlockType.FLOWER_YELLOW,
    name: 'Dente-de-Leão Amarelo',
    nameEn: 'Dandelion',
    isTransparent: true,
    isSolid: false,
    hardness: 0.05,
    sound: 'grass',
    dropBlock: BlockType.FLOWER_YELLOW,
    dropCount: 1,
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: 'Tocha',
    nameEn: 'Torch',
    isTransparent: true,
    isSolid: false,
    emitsLight: 14,
    hardness: 0.05,
    sound: 'wood',
    dropBlock: BlockType.TORCH,
    dropCount: 1,
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    name: 'Dinamite (TNT)',
    nameEn: 'TNT',
    isTransparent: false,
    isSolid: true,
    hardness: 0.1,
    sound: 'grass',
    dropBlock: BlockType.TNT,
    dropCount: 1,
  },
  [BlockType.BEDROCK]: {
    id: BlockType.BEDROCK,
    name: 'Rocha Matriz',
    nameEn: 'Bedrock',
    isTransparent: false,
    isSolid: true,
    hardness: Infinity, // unbreakable!
    sound: 'stone',
    dropBlock: BlockType.AIR,
    dropCount: 0,
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: 'Obsidiana',
    nameEn: 'Obsidian',
    isTransparent: false,
    isSolid: true,
    hardness: 5.0,
    sound: 'stone',
    dropBlock: BlockType.OBSIDIAN,
    dropCount: 1,
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    name: 'Estante de Livros',
    nameEn: 'Bookshelf',
    isTransparent: false,
    isSolid: true,
    hardness: 1.5,
    sound: 'wood',
    dropBlock: BlockType.WOOD_PLANKS,
    dropCount: 3,
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    name: 'Bancada de Trabalho',
    nameEn: 'Crafting Table',
    isTransparent: false,
    isSolid: true,
    hardness: 1.2,
    sound: 'wood',
    dropBlock: BlockType.CRAFTING_TABLE,
    dropCount: 1,
  },
  [BlockType.STICK]: {
    id: BlockType.STICK,
    name: 'Graveto',
    nameEn: 'Stick',
    isTransparent: true,
    isSolid: false,
    hardness: 0.1,
    sound: 'wood',
    dropBlock: BlockType.STICK,
    dropCount: 1,
  },
  [BlockType.WOODEN_PICKAXE]: {
    id: BlockType.WOODEN_PICKAXE,
    name: 'Picareta de Madeira',
    nameEn: 'Wooden Pickaxe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.2,
    sound: 'wood',
    dropBlock: BlockType.WOODEN_PICKAXE,
    dropCount: 1,
    isTool: true,
    toolType: 'pickaxe',
    speedMultiplier: 2.0,
  },
  [BlockType.STONE_PICKAXE]: {
    id: BlockType.STONE_PICKAXE,
    name: 'Picareta de Pedra',
    nameEn: 'Stone Pickaxe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.3,
    sound: 'stone',
    dropBlock: BlockType.STONE_PICKAXE,
    dropCount: 1,
    isTool: true,
    toolType: 'pickaxe',
    speedMultiplier: 3.5,
  },
  [BlockType.IRON_PICKAXE]: {
    id: BlockType.IRON_PICKAXE,
    name: 'Picareta de Ferro',
    nameEn: 'Iron Pickaxe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.4,
    sound: 'stone',
    dropBlock: BlockType.IRON_PICKAXE,
    dropCount: 1,
    isTool: true,
    toolType: 'pickaxe',
    speedMultiplier: 5.5,
  },
  [BlockType.DIAMOND_PICKAXE]: {
    id: BlockType.DIAMOND_PICKAXE,
    name: 'Picareta de Diamante',
    nameEn: 'Diamond Pickaxe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.5,
    sound: 'stone',
    dropBlock: BlockType.DIAMOND_PICKAXE,
    dropCount: 1,
    isTool: true,
    toolType: 'pickaxe',
    speedMultiplier: 8.5,
  },
  [BlockType.WOODEN_AXE]: {
    id: BlockType.WOODEN_AXE,
    name: 'Machado de Madeira',
    nameEn: 'Wooden Axe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.2,
    sound: 'wood',
    dropBlock: BlockType.WOODEN_AXE,
    dropCount: 1,
    isTool: true,
    toolType: 'axe',
    speedMultiplier: 2.5,
  },
  [BlockType.STONE_AXE]: {
    id: BlockType.STONE_AXE,
    name: 'Machado de Pedra',
    nameEn: 'Stone Axe',
    isTransparent: true,
    isSolid: false,
    hardness: 0.3,
    sound: 'stone',
    dropBlock: BlockType.STONE_AXE,
    dropCount: 1,
    isTool: true,
    toolType: 'axe',
    speedMultiplier: 4.0,
  },
  [BlockType.WOODEN_SHOVEL]: {
    id: BlockType.WOODEN_SHOVEL,
    name: 'Pá de Madeira',
    nameEn: 'Wooden Shovel',
    isTransparent: true,
    isSolid: false,
    hardness: 0.2,
    sound: 'wood',
    dropBlock: BlockType.WOODEN_SHOVEL,
    dropCount: 1,
    isTool: true,
    toolType: 'shovel',
    speedMultiplier: 2.5,
  },
  [BlockType.STONE_SHOVEL]: {
    id: BlockType.STONE_SHOVEL,
    name: 'Pá de Pedra',
    nameEn: 'Stone Shovel',
    isTransparent: true,
    isSolid: false,
    hardness: 0.3,
    sound: 'stone',
    dropBlock: BlockType.STONE_SHOVEL,
    dropCount: 1,
    isTool: true,
    toolType: 'shovel',
    speedMultiplier: 4.0,
  },
  [BlockType.WOODEN_SWORD]: {
    id: BlockType.WOODEN_SWORD,
    name: 'Espada de Madeira',
    nameEn: 'Wooden Sword',
    isTransparent: true,
    isSolid: false,
    hardness: 0.2,
    sound: 'wood',
    dropBlock: BlockType.WOODEN_SWORD,
    dropCount: 1,
    isTool: true,
    toolType: 'sword',
    speedMultiplier: 1.5,
  },
  [BlockType.STONE_SWORD]: {
    id: BlockType.STONE_SWORD,
    name: 'Espada de Pedra',
    nameEn: 'Stone Sword',
    isTransparent: true,
    isSolid: false,
    hardness: 0.3,
    sound: 'stone',
    dropBlock: BlockType.STONE_SWORD,
    dropCount: 1,
    isTool: true,
    toolType: 'sword',
    speedMultiplier: 2.2,
  },
  [BlockType.FURNACE]: {
    id: BlockType.FURNACE,
    name: 'Fornalha de Pedra',
    nameEn: 'Furnace',
    isTransparent: false,
    isSolid: true,
    hardness: 2.0,
    sound: 'stone',
    dropBlock: BlockType.COBBLESTONE,
    dropCount: 8,
  },
  [BlockType.ROTTEN_FLESH]: {
    id: BlockType.ROTTEN_FLESH,
    name: 'Carne Podre',
    nameEn: 'Rotten Flesh',
    isTransparent: true,
    isSolid: false,
    hardness: 0.1,
    sound: 'grass',
    dropBlock: BlockType.ROTTEN_FLESH,
    dropCount: 1,
    isTool: false,
  },
  [BlockType.BONE]: {
    id: BlockType.BONE,
    name: 'Osso de Esqueleto',
    nameEn: 'Bone',
    isTransparent: true,
    isSolid: false,
    hardness: 0.2,
    sound: 'stone',
    dropBlock: BlockType.BONE,
    dropCount: 1,
    isTool: false,
  },
  [BlockType.ARROW]: {
    id: BlockType.ARROW,
    name: 'Flecha Afiada',
    nameEn: 'Arrow',
    isTransparent: true,
    isSolid: false,
    hardness: 0.1,
    sound: 'wood',
    dropBlock: BlockType.ARROW,
    dropCount: 1,
    isTool: false,
  },
  [BlockType.BOW]: {
    id: BlockType.BOW,
    name: 'Arco de Caça',
    nameEn: 'Bow',
    isTransparent: true,
    isSolid: false,
    hardness: 0.3,
    sound: 'wood',
    dropBlock: BlockType.BOW,
    dropCount: 1,
    isTool: true,
    toolType: 'sword',
    speedMultiplier: 1.5,
  },
};

export const CHUNK_SIZE_X = 16;
export const CHUNK_SIZE_Z = 16;
export const CHUNK_HEIGHT = 48;
export const WATER_LEVEL = 12;

export interface Recipe {
  id: string;
  name: string;
  category: 'tools' | 'blocks' | 'basic';
  result: { block: BlockType; count: number };
  ingredients: { block: BlockType; count: number }[];
  description: string;
  grid?: (BlockType | null)[]; // 3x3 pattern representation (length 9)
}

export const CRAFTING_RECIPES: Recipe[] = [
  // Basic Resources
  {
    id: 'planks',
    name: 'Tábuas de Madeira (4x)',
    category: 'basic',
    result: { block: BlockType.WOOD_PLANKS, count: 4 },
    ingredients: [{ block: BlockType.WOOD_LOG, count: 1 }],
    description: '1 Tronco bruto produz 4 Tábuas resistentes.',
    grid: [
      null, null, null,
      null, BlockType.WOOD_LOG, null,
      null, null, null,
    ],
  },
  {
    id: 'stick',
    name: 'Gravetos de Madeira (4x)',
    category: 'basic',
    result: { block: BlockType.STICK, count: 4 },
    ingredients: [{ block: BlockType.WOOD_PLANKS, count: 2 }],
    description: '2 Tábuas de madeira formam 4 Gravetos essenciais para ferramentas.',
    grid: [
      null, BlockType.WOOD_PLANKS, null,
      null, BlockType.WOOD_PLANKS, null,
      null, null, null,
    ],
  },
  {
    id: 'fertile_dirt',
    name: 'Terra Fértil & Grama (2x)',
    category: 'basic',
    result: { block: BlockType.GRASS, count: 2 },
    ingredients: [
      { block: BlockType.DIRT, count: 1 },
      { block: BlockType.WOOD_LOG, count: 1 },
    ],
    description: 'Combine terra com matéria orgânica vegetal para enriquecer o solo com grama.',
    grid: [
      null, BlockType.DIRT, null,
      null, BlockType.WOOD_LOG, null,
      null, null, null,
    ],
  },
  {
    id: 'torch',
    name: 'Tochas Iluminadas (4x)',
    category: 'basic',
    result: { block: BlockType.TORCH, count: 4 },
    ingredients: [
      { block: BlockType.COAL_ORE, count: 1 },
      { block: BlockType.STICK, count: 1 },
    ],
    description: '1 Carvão no topo de 1 Graveto cria 4 Tochas brilhantes.',
    grid: [
      null, BlockType.COAL_ORE, null,
      null, BlockType.STICK, null,
      null, null, null,
    ],
  },

  // Tools & Weapons
  {
    id: 'stone_pickaxe',
    name: 'Picareta de Pedra',
    category: 'tools',
    result: { block: BlockType.STONE_PICKAXE, count: 1 },
    ingredients: [
      { block: BlockType.COBBLESTONE, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Minera pedra, minérios e pedregulhos 3.5x mais rápido!',
    grid: [
      BlockType.COBBLESTONE, BlockType.COBBLESTONE, BlockType.COBBLESTONE,
      null, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'wooden_pickaxe',
    name: 'Picareta de Madeira',
    category: 'tools',
    result: { block: BlockType.WOODEN_PICKAXE, count: 1 },
    ingredients: [
      { block: BlockType.WOOD_PLANKS, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Ferramenta básica para quebrar pedras e extrair os primeiros minérios (2.0x).',
    grid: [
      BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS,
      null, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'stone_axe',
    name: 'Machado de Pedra',
    category: 'tools',
    result: { block: BlockType.STONE_AXE, count: 1 },
    ingredients: [
      { block: BlockType.COBBLESTONE, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Corta árvores e troncos de madeira com velocidade quadruplicada (4.0x)!',
    grid: [
      BlockType.COBBLESTONE, BlockType.COBBLESTONE, null,
      BlockType.COBBLESTONE, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'wooden_axe',
    name: 'Machado de Madeira',
    category: 'tools',
    result: { block: BlockType.WOODEN_AXE, count: 1 },
    ingredients: [
      { block: BlockType.WOOD_PLANKS, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Corta troncos e madeira 2.5x mais rápido.',
    grid: [
      BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS, null,
      BlockType.WOOD_PLANKS, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'stone_shovel',
    name: 'Pá de Pedra',
    category: 'tools',
    result: { block: BlockType.STONE_SHOVEL, count: 1 },
    ingredients: [
      { block: BlockType.COBBLESTONE, count: 1 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Escava terra, grama, areia e neve instantaneamente (4.0x)!',
    grid: [
      null, BlockType.COBBLESTONE, null,
      null, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'stone_sword',
    name: 'Espada de Pedra',
    category: 'tools',
    result: { block: BlockType.STONE_SWORD, count: 1 },
    ingredients: [
      { block: BlockType.COBBLESTONE, count: 2 },
      { block: BlockType.STICK, count: 1 },
    ],
    description: 'Lâmina de combate forjada em pedra firme para proteção.',
    grid: [
      null, BlockType.COBBLESTONE, null,
      null, BlockType.COBBLESTONE, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'iron_pickaxe',
    name: 'Picareta de Ferro',
    category: 'tools',
    result: { block: BlockType.IRON_PICKAXE, count: 1 },
    ingredients: [
      { block: BlockType.IRON_ORE, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'Mineração veloz e resistente a rochas maciças (5.5x).',
    grid: [
      BlockType.IRON_ORE, BlockType.IRON_ORE, BlockType.IRON_ORE,
      null, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },
  {
    id: 'diamond_pickaxe',
    name: 'Picareta de Diamante',
    category: 'tools',
    result: { block: BlockType.DIAMOND_PICKAXE, count: 1 },
    ingredients: [
      { block: BlockType.DIAMOND_ORE, count: 3 },
      { block: BlockType.STICK, count: 2 },
    ],
    description: 'A mais poderosa e reluzente ferramenta de mineração voxel (8.5x)!',
    grid: [
      BlockType.DIAMOND_ORE, BlockType.DIAMOND_ORE, BlockType.DIAMOND_ORE,
      null, BlockType.STICK, null,
      null, BlockType.STICK, null,
    ],
  },

  // Blocks & Construction
  {
    id: 'crafting_table',
    name: 'Bancada de Trabalho',
    category: 'blocks',
    result: { block: BlockType.CRAFTING_TABLE, count: 1 },
    ingredients: [{ block: BlockType.WOOD_PLANKS, count: 4 }],
    description: '4 Tábuas de Madeira formam uma Bancada de Trabalho clássica.',
    grid: [
      BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS, null,
      BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS, null,
      null, null, null,
    ],
  },
  {
    id: 'bricks',
    name: 'Bloco de Tijolos Nobres (2x)',
    category: 'blocks',
    result: { block: BlockType.BRICKS, count: 2 },
    ingredients: [
      { block: BlockType.DIRT, count: 2 },
      { block: BlockType.STONE, count: 1 },
    ],
    description: 'Combine terra/argila cozida e pedra para erguer alvenarias nobres.',
    grid: [
      BlockType.DIRT, BlockType.DIRT, null,
      BlockType.STONE, null, null,
      null, null, null,
    ],
  },
  {
    id: 'furnace',
    name: 'Fornalha de Pedra',
    category: 'blocks',
    result: { block: BlockType.FURNACE, count: 1 },
    ingredients: [{ block: BlockType.COBBLESTONE, count: 8 }],
    description: 'Construa uma fornalha com 8 pedregulhos ao redor do centro.',
    grid: [
      BlockType.COBBLESTONE, BlockType.COBBLESTONE, BlockType.COBBLESTONE,
      BlockType.COBBLESTONE, null, BlockType.COBBLESTONE,
      BlockType.COBBLESTONE, BlockType.COBBLESTONE, BlockType.COBBLESTONE,
    ],
  },
  {
    id: 'glass',
    name: 'Vidro Transparente (2x)',
    category: 'blocks',
    result: { block: BlockType.GLASS, count: 2 },
    ingredients: [{ block: BlockType.SAND, count: 2 }],
    description: 'Areia purificada em blocos límpidos de vidro.',
    grid: [
      null, BlockType.SAND, null,
      null, BlockType.SAND, null,
      null, null, null,
    ],
  },
  {
    id: 'tnt',
    name: 'Dinamite TNT Explosiva',
    category: 'blocks',
    result: { block: BlockType.TNT, count: 1 },
    ingredients: [
      { block: BlockType.SAND, count: 2 },
      { block: BlockType.COAL_ORE, count: 2 },
    ],
    description: 'Areia e carvão compactados em dinamite com alto poder de demolição!',
    grid: [
      BlockType.SAND, BlockType.COAL_ORE, null,
      BlockType.COAL_ORE, BlockType.SAND, null,
      null, null, null,
    ],
  },
  {
    id: 'bookshelf',
    name: 'Estante de Livros',
    category: 'blocks',
    result: { block: BlockType.BOOKSHELF, count: 1 },
    ingredients: [
      { block: BlockType.WOOD_PLANKS, count: 3 },
      { block: BlockType.WOOD_LOG, count: 1 },
    ],
    description: 'Mobiliário erudito com tábuas e madeira maciça.',
    grid: [
      BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS, BlockType.WOOD_PLANKS,
      null, BlockType.WOOD_LOG, null,
      null, null, null,
    ],
  },
  {
    id: 'arrow_pack',
    name: 'Flechas Afiadas (4x)',
    category: 'tools',
    result: { block: BlockType.ARROW, count: 4 },
    ingredients: [
      { block: BlockType.STICK, count: 1 },
      { block: BlockType.COBBLESTONE, count: 1 },
    ],
    description: 'Haste com ponta de pedra esculpida para caça e combate.',
    grid: [
      BlockType.COBBLESTONE, null, null,
      BlockType.STICK, null, null,
      null, null, null,
    ],
  },
  {
    id: 'hunting_bow',
    name: 'Arco de Caça',
    category: 'tools',
    result: { block: BlockType.BOW, count: 1 },
    ingredients: [
      { block: BlockType.STICK, count: 3 },
    ],
    description: 'Arco curvado entalhado com gravetos reforçados.',
    grid: [
      null, BlockType.STICK, null,
      BlockType.STICK, null, BlockType.STICK,
      null, BlockType.STICK, null,
    ],
  },
];
